config/routes.rb
Rails.application.routes.draw do
  root "game_rounds#new"
  get "new_game"        => "game_rounds#new"
  post "players"        => "game_rounds#create"
  get "allplayers"      => "game_rounds#show"

end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_rounds_controller.rb
class GameRoundsController < ApplicationController
	def new
	end

	def create
		game_id =  ('a'..'z').to_a.shuffle[0..7].join
		players = params[:players].split(",").map(&:strip)
		players.each do |player|
			new_player = Player.new(name: player, game_id: game_id, score: 0)
			if new_player.save
				next
			else
				render 'new'
			end
		end
		redirect_to allplayers_path
	end

	def destroy
	end

	def update

	end

	def show
		@players = Player.first.name
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_rounds_helper.rb
module GameRoundsHelper
end

app/views/game_rounds/new.html.erb
Hello, love.

<%= form_tag players_path do %>
  <%= text_field_tag(:players) %>
  <%= submit_tag "Next round" %>
<%end%>

app/views/game_rounds/show.html.erb
<%= @players %>

app/views/game_rounds/update.html.erb
Hello again, <%= @player %>.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenCritics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>